// <auto-generated />
using System;
using HelpDesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807150632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Requesting license key for Visual Studio Enterprise edition",
                            Priority = "High",
                            RaisedBy = "John Doe",
                            Status = "Open",
                            Title = "Software License Request"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 8, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unable to connect to company VPN network from home",
                            Priority = "Medium",
                            RaisedBy = "Jane Smith",
                            Status = "In Progress",
                            Title = "VPN Connectivity Issue"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 8, 3, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flickering display on primary monitor",
                            Priority = "Low",
                            RaisedBy = "Alice Johnson",
                            Status = "Closed",
                            Title = "Monitor Replacement"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
